export const SOCKET_EVENTS = {
  NEW_USER_CAME: 'NEW_USER_CAME',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_TO_ALL: 'SEND_MESSAGE_TO_ALL',
  GET_STUDENTS_LIST: 'GET_STUDENTS_LIST',
  LOGOUT_CHAT: 'LOGOUT_CHAT',
};
